### ISSUE TITLE
Need profile pics

### ISSUE THREAD

**Issue by TajjCreative** [saqlain-shah/mernStackCourse#13]
Please send your profile pics in group or inbox.
I need your pic to add in table.
Thank You

**Comment by sAjU1122** [comment]
![278379229_1029017531304613_8405769144916966352_n](https://github.com/saqlain-shah/mernStackCourse/assets/133696760/2fd255e3-d23a-4cc8-9236-c160c428d430)

**Comment by karamat-ali** [comment]
![abrar](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/ebfcf28d-698f-4a55-832a-e0b2aaad9174)

**Comment by karamat-ali** [comment]
![Awais](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/16f1c72a-61ae-488d-82ea-bd56bccb373b)
![imtiyaz](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/fa26339f-4559-476d-a657-ff8d1d56b139)
![jaffar](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/a8d589e6-2c6a-4e4b-82d0-c17c1e542cd8)
![Mehboob](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/f063809b-2371-4c80-b00e-7910a6b129da)
![Sajjad](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/174b94f7-3792-4aca-a12a-b4b9edc33651)
![usama](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/6edca96a-1782-4d84-8245-854b3ec47695)
![abrar haider](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/07cdf53b-ebe0-4fcf-9b06-7a1ec8585c77)

**Comment by karamat-ali** [comment]
![IMG-20230520-WA0060](https://github.com/saqlain-shah/mernStackCourse/assets/133817155/b845c0a7-aeb3-4d58-a038-59c7b837b5c2)
