### ISSUE TITLE
How to info on linkedin and github

### ISSUE THREAD

**Issue by Usama-Hamid324** [saqlain-shah/mernStackCourse#17]
please tell me about how to add information/# on linkedin and github

**Comment by TajjCreative** [comment]
Go to your profile and scroll down, Under Resources Creator mode option will be shown, click on creator mode, after that you see the Profile Topics, Below the profile topics you see the Add topic option, click there and add your skills.
![Capture 1](https://github.com/saqlain-shah/mernStackCourse/assets/80399185/7886c27c-c694-4277-8e6b-837eaa2ac36a)
![2](https://github.com/saqlain-shah/mernStackCourse/assets/80399185/6d806aef-76df-4a3f-8bee-7a2e5e22b82d)

**Comment by karamat-ali** [comment]
[](url)
